### Create a new appointment
GET http://localhost:3000/v1/schedules/services/1?startDate=2025-09-19T00:00:00.000Z
Content-Type: application/json
X-Tenant-Id: 1  # Example tenant ID

### Doctor's appointment
GET http://localhost:3000/v1/schedules/doctors/1/booked?from=2025-09-19T00:00:00.000Z&to=2025-09-19T00:00:00.000Z
Content-Type: application/json
X-Tenant-Id: 1  # Example tenant ID
