-- +migrator UP
CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE IF NOT EXISTS clinics (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

-- +migrator DOWN
DROP TABLE IF EXISTS clinics;
DROP EXTENSION IF EXISTS btree_gist;